name: assignment3

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build image
      run: |
        echo "$(date -Iminutes)" > log.txt
        echo "Oren Savich, Itay Tiomkin" >> log.txt
        docker build -t books-service -f books/Dockerfile books
        if [ $? -eq 0 ]; then
          echo "image successfully built" >> log.txt
        else
          echo "image not able to be built" >> log.txt
        fi
    - uses: actions/upload-artifact@v4
      with:
        name: log-file
        path: log.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      tests-passed: ${{ steps.set-output.outputs.tests-passed }}
    steps:
    - uses: actions/checkout@v4
    - name: Download log file
      uses: actions/download-artifact@v4
      with:
        name: log-file
        path: ./
    - name: Set up Docker Compose
      run: |
        docker-compose up -d
        if [ $? -eq 0 ]; then
          echo "Container up and running" >> log.txt
        else
          echo "Container failed to run" >> log.txt
        fi
    - name: Install dependencies
      run: |
        pip install pytest requests
    - name: Run tests
      id: tests-outcome
      run: |
        pytest -vv tests/assn3_tests.py | tee assn3_test_results.txt
        if [ ${PIPESTATUS[0]} -eq 0 ]; then
          echo "tests succeeded" >> log.txt
          echo "::set-output name=tests-passed::true"
        else
          echo "tests failed" >> log.txt
          echo "::set-output name=tests-passed::false"
        fi
    - name: Output test result
      run: echo "tests-passed=${{ steps.tests-outcome.outputs.tests-passed }}"
    - name: Shut down containers
      run: docker-compose down   
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: assn3_test_results.txt
    - uses: actions/upload-artifact@v4
      with:
        name: log-file
        path: log.txt
        overwrite: true

  query:
    needs: test
    runs-on: ubuntu-latest
    if: needs.test.outputs.tests-passed == 'true'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Compose
      run: docker-compose up -d
    - name: Execute queries
      run: |
        sleep 10
        for i in {1..3}; do
          while IFS= read -r query; do
            echo "Executing query: $query"
            curl -v -X GET "http://localhost:5001/$query" -o response.txt || true
            echo "Query: $query" >> query_log.txt
            echo "Response:" >> query_log.txt
            cat response.txt >> query_log.txt
            echo "\n" >> query_log.txt
          done < query.txt
          if [ $? -eq 0 ]; then
            break
          fi
          sleep 5
        done
    - uses: actions/upload-artifact@v4
      with:
        name: query-results
        path: query_log.txt
